version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build --configuration Release
      - run: dotnet test --no-build AbstractEnum.Tests
      - run: dotnet pack --output nugetPackages
      - store_artifacts:
          path: AbstractEnum.Net/nugetPackages
          destination: nugetPackages
      - persist_to_workspace:
          root: AbstractEnum.Net/
          paths:
            - nugetPackages          
  publishNuget:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - attach_workspace:
          at: .
      - run: find .
      - run: dotnet nuget push nugetPackages/*.nupkg --api-key ${NUGET_KEY} --source ${NUGET_SOURCE}
workflows:
  version: 2
  build-and-publish:
    branches:
      only: 
        - master
    jobs:
      - build
      - publishNuget:
          requires:
            - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            only:
              - master
              - develop
            
    jobs:
      - build
  commit:
    branches:
      ignore:
        - master
    jobs:
      - build

  
        