version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run: dotnet restore
      - run: apt-get update
      - run: apt-get install -y libgit2-dev
      - run: ln -s /usr/lib/x86_64-linux-gnu/libgit2.so /lib/x86_64-linux-gnu/libgit2-15e1193.so
      - run: dotnet build --configuration Release
      - run: dotnet test --no-build --configuration Release AbstractEnum.Tests
      - run: dotnet pack --output nugetPackages
      - store_artifacts:
          path: AbstractEnum.Net/nugetPackages
          destination: nugetPackages
      - persist_to_workspace:
          root: AbstractEnum.Net/
          paths:
            - nugetPackages          
  publishNuget:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - attach_workspace:
          at: .
      - run: find .
      - run: dotnet nuget push nugetPackages/*.nupkg --api-key ${NUGET_KEY} --source ${NUGET_SOURCE}
workflows:
  version: 2
  build-and-publish:  
    jobs:
      - build:
        filters:
          tags:
            only: /^v.*/
          branches:
            only: /.*/
      - publishNuget:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - develop
    jobs:
      - build

  
        