version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build AbstractEnum.Tests
      - run: dotnet pack --output nugetPackages
      - store_artifacts:
          path: AbstractEnum.Net/nugetPackages
          destination: nugetPackages
      - persist_to_workspace:
          root: .
          paths:
            - AbstractEnum.Net/nugetPackages          
  publishNuget:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - attach_workspace:
          at: .
      - run: find .
      - run: dotnet nuget push *.nupkg --api-key ${NUGET_KEY} --source ${NUGET_SOURCE}
workflows:
  version: 2
  build-and-publish:
      jobs:
        - build
        - publishNuget:
            requires:
              - build
            filters:
              branches:
                only: 
                  - master
                  - circleCiBuild
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - develop
    jobs:
      - build
#  commit:
#    jobs:
#      - build

  
        