version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build AbstractEnum.Tests
      - run: dotnet pack --output nugetTarget
      - store_artifacts:
          path: AbstractEnum.Net/nugetTarget
  publishNuget:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - run: find .
workflows:
  version: 2
  build-and-publish:
      jobs:
        - build
        - publishNuget:
            requires:
              - build
            filters:
              branches:
                only: 
                  - master
                  - circleCiBuild
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - develop
    jobs:
      - build
  commit:
    jobs:
      - build

  
        